# -*- coding: utf-8 -*-
"""Co2_emissions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gWm7PDZnnNDz1QmQ4LiV1QvZpjK7Y8kz
"""

!pip install streamlit
!wget -q -nc https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
!chmod +x cloudflared-linux-amd64

!pip install easyocr
!pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import easyocr
# import re
# import streamlit as st
# 
# 
# st.markdown("""
# <style>
# 
# @import url('https://fonts.googleapis.com/css2?family=Ranchers&display=swap');
# @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600&display=swap');
# 
# /* -----------------------------------
#    REMOVE TOP WHITE BAR
# ----------------------------------- */
# header[data-testid="stHeader"] {
#     background-color: transparent !important;
# }
# 
# /* -----------------------------------
#    MAIN BACKGROUND
# ----------------------------------- */
# html, body { /* Adding html, body for broader background application */
#     background-color: #DAF0F7 !important;
# }
# main[data-testid="stAppViewContainer"] {
#     background-color: #DAF0F7 !important;
# }
# .stApp { /* Adding a more generic selector for background */
#     background-color: #DAF0F7 !important;
# }
# 
# 
# /* -----------------------------------
#    SIDEBAR (This section will no longer be visible as the sidebar is removed)
# ----------------------------------- */
# aside[data-testid="stSidebar"] {
#     display: none !important; /* Explicitly hide sidebar */
# }
# 
# 
# /* -----------------------------------
#    TITLE (Ranchers)
# ----------------------------------- */
# h1, h1 span, h1 div {
#     font-family: 'Ranchers', cursive !important;
#     color: #333333 !important;
#     text-align: center !important;
#     font-size: 48px !important;
# }
# 
# /* -----------------------------------
#    BODY TEXT (Inter)
# ----------------------------------- */
# html, body, p, label, span, div, input, textarea {
#     font-family: 'Inter', sans-serif !important;
#     color: #333333;
# }
# 
# /* Centered text */
# .centered-text {
#     text-align: center;
# }
# 
# /* -----------------------------------
#    BUTTONS (Green accent)
# ----------------------------------- */
# div.stButton > button {
#     background-color: #BEF754 !important;
#     color: #333333 !important;
#     border-radius: 10px !important;
#     padding: 10px 20px !important;
#     border: none !important;
#     font-size: 16px !important;
#     font-weight: 500 !important;
# }
# div.stButton > button:hover {
#     background-color: #A6D94A !important;
# }
# 
# /* -----------------------------------
#    FILE UPLOADER — FIX DOUBLE TEXT
# ----------------------------------- */
# 
# /* Hide default "Drag and drop file here or browse files" text inside the uploader */
# [data-testid="stFileUploaderDropzone"] p {
#     display: none !important;
# }
# 
# /* Styling for the actual "Browse files" button within the uploader */
# [data-testid="stFileUploader"] button {
#     padding: 12px 25px !important; /* Increased padding */
#     font-size: 18px !important; /* Increased font size */
#     min-width: 120px; /* Ensure a minimum width - Adjusted */
#     height: auto; /* Allow height to adjust */
# }
# 
# 
# /* Style uploader box */
# [data-testid="stFileUploader"] {
#     border: 2px dashed #BC9E82 !important; /* Use sidebar color for consistency */
#     border-radius: 12px;
#     padding: 20px;
#     background: white;
# }
# 
# /* -----------------------------------
#    CARD STYLE
# ----------------------------------- */
# 
# .card {
#     background: white;
#     padding: 25px;
#     border-radius: 15px;
#     box-shadow: 0 4px 12px rgba(0,0,0,0.1);
#     margin-bottom: 20px;
# }
# 
# /* Progress bar */
# [data-testid="stProgress"] > div > div {
#     background-color: #BEF754;
# }
# 
# /* Highlight text (if used) */
# .highlight {
#     color: #BEF754;
#     font-weight: 600;
# }
# 
# </style>
# """, unsafe_allow_html=True)
# 
# 
# # Initialize session state for page navigation
# if "page" not in st.session_state:
#     st.session_state.page = "input"
# 
# @st.cache_resource
# def load_easyocr():
#     import easyocr
#     return easyocr.Reader(['en'], gpu=False)
# 
# @st.cache_resource
# def load_paddleocr():
#     from paddleocr import PaddleOCR
#     return PaddleOCR(use_angle_cls=True, lang='en')
# 
# 
# emission_factors = {
#     "Cotton": 2.1,
#     "Organic Cotton": 1.6,
#     "Recycled Cotton": 1.0,
#     "Polyester": 5.5,
#     "Recycled Polyester": 3.0,
#     "Nylon": 9.0,
#     "Recycled Nylon": 5.5,
#     "Wool": 13.0,
#     "Cashmere": 30.0,
#     "Elastane": 5.0,
#     "Viscose": 3.0,
#     "Modal": 2.8,
#     "Lyocell (Tencel)": 2.0,
#     "Bamboo Viscose": 3.5,
#     "Linen": 2.4,
#     "Hemp": 1.5,
#     "Silk": 10.0,
#     "Acrylic": 6.0,
#     "Leather": 17.0,
#     "Other": 4.0
# }
# 
# def reset():
#     st.session_state.page = "input"
#     if "uploaded_file" in st.session_state:
#         del st.session_state.uploaded_file
#     if "image_bytes" in st.session_state:
#         del st.session_state.image_bytes
#     if "materials" in st.session_state:
#         del st.session_state.materials
# 
# # The sidebar has been removed entirely based on your request.
# 
# 
# # Page 1: Input (Upload or Manual Text)
# if st.session_state.page == "input":
# 
#     # Hero GIF
#     st.markdown(
#         """
#         <div style='text-align: center; margin-top: 20px;'>
#             <img src="https://media4.giphy.com/media/v1.Y2lkPTc5MGI3NjExeW9kb21qb3J4MHpsNG5xejJ5ZnFzcWJlczkwd3l4dmQxeGZ1M2x3YyZlcD12MV9pbnRlcm5uYWxfnaWZfYnlfaWQmY3Q9Zw/l0MYPsBLOYyFqSDte/giphy.gif"
#                  style="width: 280px; border-radius: 12px;">
#         </div>
#         """,
#         unsafe_allow_html=True
#     )
# 
#     # Title
#     st.markdown("<h1 style='text-align:center;'>Fashion Material Impact Calculator</h1>", unsafe_allow_html=True)
# 
#     st.markdown("<p class='centered-text'>Let's check your cute items, how much they effect the environment U・x・U</p>", unsafe_allow_html=True)
# 
#     # Custom subheader for the uploader
#     st.subheader("📸 Upload the picture of your lovely item's label 👗")
#     # Modified st.file_uploader to hide its default label
#     uploaded_file = st.file_uploader("", type=["jpg", "png"], label_visibility="hidden") # Changed label to empty string and visibility to hidden
# 
#     st.write("### If you haven't bought it yet...")
# 
#     if st.button("Enter Materials Manually"):
#         st.session_state.page = "manual"
#         st.rerun()
# 
#     if uploaded_file:
#         if st.button("Next"):
#             st.session_state.uploaded_file = uploaded_file
#             st.session_state.page = "process"
#             st.rerun()
# 
# # Page 2: Processing
# elif st.session_state.page == "process":
#     st.title("⏳Processing your item...⏳")
# 
#     # Read image bytes once and store in session state if not already done
#     if "image_bytes" not in st.session_state and st.session_state.get("uploaded_file"):
#         st.session_state.image_bytes = st.session_state.uploaded_file.read()
#         del st.session_state.uploaded_file # Clear the UploadedFile object
# 
#     # Proceed only if image bytes are available
#     if "image_bytes" in st.session_state and st.session_state.image_bytes:
#         with st.spinner("Reading your label with AI..."):
#             # -----------------------------
#             # 1. Load OCR models
#             # -----------------------------
#             from paddleocr import PaddleOCR
#             import openai # Keep import for LLM placeholder consistency
# 
#             easy_reader = load_easyocr()
#             paddle_reader = load_paddleocr()
# 
#             # -----------------------------
#             # 2. Prepare image for processing
#             # -----------------------------
#             image_bytes_to_process = st.session_state.image_bytes
# 
#             # -----------------------------
#             # 3. EasyOCR attempt
#             # -----------------------------
#             easy_text = " ".join(easy_reader.readtext(image_bytes_to_process, detail=0))
#             # st.write("EasyOCR extracted:")
#             # st.write(easy_text)
# 
#             # -----------------------------
#             # 4. PaddleOCR attempt
#             # -----------------------------
#             paddle_result = paddle_reader.ocr(image_bytes_to_process)
#             paddle_text = ""
#             if paddle_result and paddle_result[0]: # Check if paddle_result is not empty and its first element exists
#                 paddle_text = " ".join([line[1][0] for line in paddle_result[0]])
#             # st.write("PaddleOCR extracted:")
#             # st.write(paddle_text)
# 
#             # -----------------------------
#             # 5. Combine OCR outputs
#             # -----------------------------
#             combined_raw = easy_text + " " + paddle_text
#             cleaned = combined_raw.upper()
# 
#             # -----------------------------
#             # 6. LLM text cleaning
#             # -----------------------------
#             prompt = """
#             Clean this OCR text from a clothing label. Fix spelling, remove noise,
#             and output only the material composition lines:
# 
#             OCR TEXT:
#             {combined_raw}
# 
#             Return only cleaned text.
#             """
# 
#             try:
#                 # Placeholder for actual LLM call
#                 llm_cleaned = cleaned # Directly use cleaned OCR text as LLM output if API is not configured
#             except Exception as e:
#                 st.warning(f"LLM processing failed (is OpenAI API key set and 'openai' installed?): {e}")
#                 llm_cleaned = cleaned # Fallback to cleaned OCR text if LLM fails
#                 st.write("Falling back to direct OCR text for material extraction.")
# 
#             # -----------------------------
#             # 7. Extract materials
#             # -----------------------------
#             pattern = r"(\d+)%\s*([A-Z]+)"
#             matches = re.findall(pattern, llm_cleaned)
# 
#             extracted = [(mat, int(pct)) for pct, mat in matches]
# 
#             # Fuzzy fallback
#             cotton_variants = ["COTTON", "COTT", "COTN", "COT", "COLL", "COJ"]
#             if not extracted:
#                 if any(v in llm_cleaned for v in cotton_variants):
#                     extracted = [("COTTON", 100)]
# 
#             # -----------------------------
#             # 8. Confidence scoring
#             # -----------------------------
#             confidence = 0
#             if "COT" in easy_text.upper():
#                 confidence += 30
#             if "COT" in paddle_text.upper():
#                 confidence += 30
#             if "COTTON" in llm_cleaned:
#                 confidence += 40
# 
#             # -----------------------------
#             # 9. User confirmation
#             # -----------------------------
#             if extracted:
#                 material_name, pct = extracted[0]
#                 st.write(f"AI thinks your item is **{pct}% {material_name}**")
# 
#                 if st.button("Yes, this is correct ^_^"):
#                     st.session_state.materials = [(material_name, pct)] # Store as list of tuples
#                     st.session_state.page = "results"
#                     st.rerun()
# 
#                 if st.button("No, enter manually T^T"):
#                     st.session_state.page = "manual"
#                     st.rerun()
#             else:
#                 st.warning("AI could not confidently extract materials, sorry...")
#                 if st.button("Continue manually"):
#                     st.session_state.page = "manual"
#                     st.rerun()
#     else:
#         st.warning("No image was uploaded or image data is missing. Please go back to the input page.")
#         if st.button("Go back to input"):
#             st.session_state.page = "input"
#             st.rerun()
# 
# 
# # Page 3: Manual Material Composition Input (adapted from original app.py)
# elif st.session_state.page == "manual":
#     st.title("Material Composition Input")
# 
#     material_options = [
#         "Cotton",
#         "Organic Cotton",
#         "Recycled Cotton",
#         "Polyester",
#         "Recycled Polyester",
#         "Nylon",
#         "Recycled Nylon",
#         "Wool",
#         "Cashmere",
#         "Elastane",
#         "Viscose",
#         "Modal",
#         "Lyocell (Tencel)",
#         "Bamboo Viscose",
#         "Linen",
#         "Hemp",
#         "Silk",
#         "Acrylic",
#         "Leather",
#         "Other"
#     ]
# 
#     num_materials = st.number_input("How many materials does the item have?", min_value=1, max_value=5, value=1)
# 
#     materials = []
# 
#     for i in range(num_materials):
#         st.subheader(f"Material {i+1}")
# 
#         material = st.selectbox(f"Select material {i+1}", material_options, key=f"material_{i}")
#         percentage = st.number_input(f"Percentage of {material}", min_value=0, max_value=100, key=f"percent_{i}")
# 
#         materials.append((material, percentage))
# 
#     total = sum([p for _, p in materials])
# 
#     st.write(f"Total percentage: **{total}%**")
# 
#     if total != 100:
#         st.warning("Total must be 100%")
#     else:
#         st.success("Perfect! Ready to calculate CO₂.")
#         if st.button("Calculate CO₂"):
#             st.session_state.materials = materials
#             st.session_state.page = "results"
#             st.rerun()
# 
# # Page 4: Results
# elif st.session_state.page == "results":
#     st.title("Environmental Impact Results")
# 
#     # Emission GIF
#     st.markdown(
#         """
#         <div style='text-align: center; margin-top: 10px;'>
#             <img src="https://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExaTUwZnc2d3ZqYmh6ZG13bWF1azM2ODVkaXV1OXEwNHp5aWI4OHkxYiZlcD12MV9pbnRlcm5uYWxfZ2lmX2J5X2lkJmN0PXc/0a253t0yVl2IqWz9Qq/giphy.gif"
#                  style="width: 220px; border-radius: 12px;">
#         </div>
#         """,
#         unsafe_allow_html=True
#     )
# 
#     if "materials" in st.session_state:
#         materials = st.session_state.materials
# 
#         emission_factors = {
#             "Cotton": 2.1, "Organic Cotton": 1.6, "Recycled Cotton": 1.0,
#             "Polyester": 5.5, "Recycled Polyester": 3.0,
#             "Nylon": 9.0, "Recycled Nylon": 5.5,
#             "Wool": 13.0, "Cashmere": 30.0,
#             "Elastane": 5.0, "Viscose": 3.0, "Modal": 2.8,
#             "Lyocell (Tencel)": 2.0, "Bamboo Viscose": 3.5,
#             "Linen": 2.4, "Hemp": 1.5,
#             "Silk": 10.0, "Acrylic": 6.0,
#             "Leather": 17.0, "Other": 4.0
#         }
# 
#         total_co2 = sum((pct/100) * emission_factors.get(mat, 4.0) for mat, pct in materials)
# 
#         st.subheader("Estimated CO₂ Emissions")
#         st.write(f"**{total_co2:.2f} kg CO₂e per item**")
# 
#         st.subheader("What does this mean?")
#         st.write(f"- Equivalent to driving **{total_co2/0.19:.1f} km 🚙**")
#         st.write(f"- Equivalent to **{total_co2/0.09:.0f} cups of coffee ☕️**")
#         st.write(f"- Equivalent to **{total_co2/0.008:.0f} phone charges 🪫**")
# 
#     if st.button("Go back to input"):
#         st.session_state.page = "input"
#         st.rerun()

# Kill any existing streamlit or cloudflared processes
!killall streamlit &>/dev/null
!killall cloudflared &>/dev/null

# Run Streamlit in the background
!streamlit run app.py --server.port 8501 &>/dev/null &

# Start cloudflared tunnel and capture its output
import subprocess
import re
import time

process = subprocess.Popen(['./cloudflared-linux-amd64', 'tunnel', '--url', 'http://localhost:8501', '--no-autoupdate'],
                           stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)

public_url = None
for i in range(10): # Try to find the URL for a few seconds
    line = process.stderr.readline()
    print(line, end='') # Print cloudflared's stderr to see its progress
    match = re.search(r'https://[-0-9a-z]+\.trycloudflare\.com', line)
    if match:
        public_url = match.group(0)
        break
    time.sleep(1)

if public_url:
    print(f"\nYour Streamlit app is publicly accessible at: {public_url}")
else:
    print("Could not find the public URL. Please check the cloudflared output for errors.")